looking:TestContext.checkException
private synchronized void checkException() throws Exception {
    if (err != null) {
        throw new RuntimeException("Deferred", err);
    }
}

private synchronized void checkException() throws Exception {
    if (err != null) {
        throw new RuntimeException("Deferred", err);
    }
}
possible Hot1
